In [1]:
from numpy import array, matrix
import pprint

In [2]:
A = matrix ( [[2, 5, 11],[21, 9, 3]] )
print (A)

[[ 2  5 11]
 [21  9  3]]


In [3]:
B = matrix ( [[4, 5],[11, 7],[3, -6]] )
print (B)

[[ 4  5]
 [11  7]
 [ 3 -6]]


In [4]:
C = matrix ( [[4, 1, 0],[-2, -9, 6]])
print (C)

[[ 4  1  0]
 [-2 -9  6]]


In [5]:
D = matrix ( [[3, 4],[5, 1],[8, 0]] )
print (D)

[[3 4]
 [5 1]
 [8 0]]


what is A + C

In [6]:
print (A + C)

[[ 6  6 11]
 [19  0  9]]


what is A + B

In [7]:
print (A + B)

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

what is B - D

In [ ]:
print (B - D)

[[ 1  1]
 [ 6  6]
 [-5 -6]]


what is 2A - 3C

In [9]:
print (2 * A) 

[[ 4 10 22]
 [42 18  6]]


In [10]:
print (3 * C)

[[ 12   3   0]
 [ -6 -27  18]]


In [11]:
print ( (2 * A) - (3 * C) ) 

[[ -8   7  22]
 [ 48  45 -12]]


what is the order of A

In [13]:
print (A.shape[0], "x", A.shape[1])

2 x 3
